version: "3.3"

services:
  web:
      build: .
      depends_on:
        - db
      restart: always
      expose:
        - 8000

  nginx:
    build: nginx
    depends_on:
      - web
    ports:
      - 80:80
    restart: always

  db:
      image: postgres:14.0
      restart: always
      env_file:
        - envs/.env
      volumes:
          - db-data:/var/lib/postgresql/data
      expose:
          - 5432
volumes:
  db-data:
